import { Navbar } from "@/components/NavBar/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

//TODO import this properly as an actual package once I figure out why the heck next can't find this
import { INavbarProps } from "../../../shared_types/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navbarEntry: INavbarProps = await fetch(
    "http://localhost:3000/components/navbar"
  ).then((response) => {
    return response.json().then((result) => {
      return result;
    });
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar title="something" navbarItems={navbarEntry.navbarItems} />
        {children}
      </body>
    </html>
  );
}
