import { Navbar } from "@/components/NavBar/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { createClient } from "contentful";
import { INavbar } from "@/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navbarEntry: INavbar = await fetch(
    "http://localhost:3000/components/navbar"
  ).then((response) => {
    return response.json().then((result) => {
      return result;
    });
  });

  console.log(typeof navbarEntry);
  console.log(navbarEntry);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar navItems={navbarEntry.navItems} />
        {children}
      </body>
    </html>
  );
}
