import { Navbar } from "@/components/NavBar/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { createClient } from "contentful";
import { INavbar } from "@/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const client = createClient({
    space: "wd2ucjfyw3mc",
    environment: "master",
    accessToken: "0yoCyfXL6MdGSygxgrb9R2WG5LNJMlSABzuq5IoMSAg",
  });

  const navbarEntry = await client
    .getEntry<INavbar>("lHxi89ELKIjfqHw4tz2I6")
    .then((entry) => entry);

  console.log(navbarEntry);
  console.log(navbarEntry.fields.navbarItems);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar navItems={navbarEntry.fields.navbarItems} />
        {children}
      </body>
    </html>
  );
}
